// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm0DlmiBlRwWIwppkBFyD0ZDmYwUdIKpw',
    appId: '1:577725617352:web:6d32236e39198bef55c1fd',
    messagingSenderId: '577725617352',
    projectId: 'internal-assessment-version-3',
    authDomain: 'internal-assessment-version-3.firebaseapp.com',
    storageBucket: 'internal-assessment-version-3.appspot.com',
    measurementId: 'G-KK9LJ10L8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6lNv_dHvt69ockAkMlmPVyHN7iNFiXdI',
    appId: '1:577725617352:android:b57542614377661555c1fd',
    messagingSenderId: '577725617352',
    projectId: 'internal-assessment-version-3',
    storageBucket: 'internal-assessment-version-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNgFa9TDeo8Q-N7Nu8K-ZZmgonsn2sHM',
    appId: '1:577725617352:ios:1f5d304b3366fefb55c1fd',
    messagingSenderId: '577725617352',
    projectId: 'internal-assessment-version-3',
    storageBucket: 'internal-assessment-version-3.appspot.com',
    iosBundleId: 'com.example.internalAssessmentV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADNgFa9TDeo8Q-N7Nu8K-ZZmgonsn2sHM',
    appId: '1:577725617352:ios:1f0c462511d92ce255c1fd',
    messagingSenderId: '577725617352',
    projectId: 'internal-assessment-version-3',
    storageBucket: 'internal-assessment-version-3.appspot.com',
    iosBundleId: 'com.example.internalAssessmentV3.RunnerTests',
  );
}
